# ===============================
# CONFIGURA플O DO SERVIDOR
# ===============================

server.port=8080

# ===============================
# CONFIGURA플O DO BANCO DE DADOS
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:2714/barbearia
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURA플O DO JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURA플O DE LOG (OPCIONAL)
# ===============================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE